In [2]:
import pandas as pd

song = pd.read_csv("data/spotify/spotify_global_2019_most_streamed_tracks_audio_features.csv")

In [3]:
song.head(10)

,Country,Rank,Track_id,Streams,Track Name,Artist,URL,acousticness,danceability,energy,...,valence,tempo,time_signature,duration_ms,key,mode,Artist_id,Artist_popularity,Artist_follower,Artist_img
0,global,1.0,25sgk305KZfyuqVBQIahim,1166185736,Sweet but Psycho,Ava Max,https://open.spotify.com/track/25sgk305KZfyuqV...,0.0691,0.719,0.704,...,0.628,133.002,4,187436,1,1,4npEfmQ6YuiwW1GpUmaq3F,87,1025358,https://i.scdn.co/image/4b914c6470c8458674538a...
1,global,2.0,2Fxmhks0bxGSBdJ92vM42m,1052358787,bad guy,Billie Eilish,https://open.spotify.com/track/2Fxmhks0bxGSBdJ...,0.3280,0.701,0.425,...,0.562,135.128,4,194088,7,1,6qqNVTkY8uBg9cP3Jd7DAH,98,18867904,https://i.scdn.co/image/2622edec99d68d1d141886...
2,global,3.0,6ocbgoVGwYJhOv1GgI9NsF,789094044,7 rings,Ariana Grande,https://open.spotify.com/track/6ocbgoVGwYJhOv1...,0.5920,0.778,0.317,...,0.327,140.048,4,178627,1,0,66CXWjxzNUsdJxJ2JdwvnR,97,40958727,https://i.scdn.co/image/b1dfbe843b0b9f54ab2e58...
3,global,4.0,1rgnBhdG2JDFTbYkYRZAku,764208309,Dance Monkey,Tones and I,https://open.spotify.com/track/1rgnBhdG2JDFTbY...,0.6880,0.825,0.593,...,0.540,98.078,4,209755,6,0,2NjfBq1NflQcKSeiDooVjY,92,484241,https://i.scdn.co/image/c128f5ef4d210a67610acd...
4,global,5.0,6v3KW9xbzN5yKLt9YKDYA2,763064359,Señorita,Shawn Mendes,https://open.spotify.com/track/6v3KW9xbzN5yKLt...,0.0392,0.759,0.548,...,0.749,116.967,4,190800,9,0,7n2wHs1TKAczGzO7Dd2rGr,94,23152263,https://i.scdn.co/image/6bd59cfbd3e1e6394af710...
5,global,6.0,5w9c2J52mkdntKOmRLeM2m,715027898,Con Calma,Daddy Yankee,https://open.spotify.com/track/5w9c2J52mkdntKO...,0.1100,0.737,0.860,...,0.656,93.989,4,193227,8,0,4VMYDCV2IEDYJArk749S6m,95,15857952,https://i.scdn.co/image/01dae15758ba1a3d18e6e3...
6,global,7.0,2VxeLyX666F8uXCJ0dZF8B,714097238,Shallow,Lady Gaga,https://open.spotify.com/track/2VxeLyX666F8uXC...,0.3710,0.572,0.385,...,0.323,95.799,4,215733,7,1,1HY2Jd0NmPuamShAr6KMms,89,10181517,https://i.scdn.co/image/ea76c82c05174105751f85...
7,global,8.0,7qEHsqek33rTcFNT9PFqLf,661930419,Someone You Loved,Lewis Capaldi,https://open.spotify.com/track/7qEHsqek33rTcFN...,0.7510,0.501,0.405,...,0.446,109.891,4,182161,1,1,4GNC7GD6oZMSxPGyXy4MNB,92,2143489,https://i.scdn.co/image/5ed13d249e562fea4e296a...
8,global,9.0,2dpaYNEQHiRxtZbfNsse99,620829467,Happier,Marshmello,https://open.spotify.com/track/2dpaYNEQHiRxtZb...,0.1910,0.687,0.792,...,0.671,100.015,4,214290,5,1,64KEffDW9EtZ1y2vBYgq8T,90,20341696,https://i.scdn.co/image/eb88f6dde0844337248826...
9,global,10.0,6MWtB6iiXyIwun0YzU6DFP,615519053,Wow.,Post Malone,https://open.spotify.com/track/6MWtB6iiXyIwun0...,0.1630,0.833,0.539,...,0.385,99.947,4,149520,11,0,246dkjvS1zLTtiykXe5h60,100,21335421,https://i.scdn.co/image/93fec27f9aac86526b9010...

In [5]:
song.info()

<class 'pandas.DataFrame'>
RangeIndex: 1717 entries, 0 to 1716
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            1717 non-null   str
 1   Rank               1717 non-null   float64
 2   Track_id           1717 non-null   str
 3   Streams            1717 non-null   int64
 4   Track Name         1717 non-null   str
 5   Artist             1717 non-null   str
 6   URL                1717 non-null   str
 7   acousticness       1717 non-null   float64
 8   danceability       1717 non-null   float64
 9   energy             1717 non-null   float64
 10  instrumentalness   1717 non-null   float64
 11  liveness           1717 non-null   float64
 12  loudness           1717 non-null   float64
 13  speechiness        1717 non-null   float64
 14  valence            1717 non-null   float64
 15  tempo              1717 non-null   float64
 16  time_signature     1717 non-null   int64
 17  duration_ms        1717 non-null   int64
 18  key                1717 non-null   int64
 19  mode               1717 non-null   int64
 20  Artist_id          1717 non-null   str
 21  Artist_popularity  1717 non-null   int64
 22  Artist_follower    1717 non-null   int64
 23  Artist_img         1717 non-null   str
dtypes: float64(10), int64(7), str(7)
memory usage: 322.1 KB

In [8]:
song.describe()

,Rank,Streams,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,valence,tempo,time_signature,duration_ms,key,mode,Artist_popularity,Artist_follower
count,1717.000000,1.717000e+03,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1717.000000,1.717000e+03
mean,859.000000,5.166175e+07,0.257652,0.675438,0.624354,0.014577,0.174317,-6.477624,0.129967,0.487719,122.147556,3.942341,202604.382644,5.332557,0.582994,87.246942,8.645130e+06
std,495.799523,1.047532e+08,0.256975,0.154163,0.172298,0.085988,0.135992,2.777252,0.113958,0.220402,30.734280,0.373427,58229.593358,3.677810,0.493208,7.808209,1.105793e+07
min,1.000000,5.242300e+05,0.000037,0.151000,0.013700,0.000000,0.019700,-25.166000,0.023200,0.026200,46.489000,1.000000,46837.000000,0.000000,0.000000,47.000000,1.090000e+02
25%,430.000000,1.763026e+06,0.051900,0.584000,0.525000,0.000000,0.097200,-7.595000,0.044600,0.321000,97.038000,4.000000,171573.000000,2.000000,0.000000,83.000000,1.370858e+06
50%,859.000000,9.623926e+06,0.171000,0.694000,0.646000,0.000000,0.123000,-5.991000,0.080100,0.490000,120.013000,4.000000,196400.000000,6.000000,1.000000,87.000000,3.998147e+06
75%,1288.000000,4.829352e+07,0.385000,0.787000,0.747000,0.000022,0.198000,-4.696000,0.188000,0.652000,143.027000,4.000000,224225.000000,8.000000,1.000000,93.000000,1.099547e+07
max,1717.000000,1.166186e+09,0.979000,0.974000,0.978000,0.956000,0.959000,-1.339000,0.856000,0.982000,207.476000,5.000000,943529.000000,11.000000,1.000000,100.000000,5.746376e+07

In [9]:
df = song[["Rank", "Artist", "Track Name", "Artist_popularity", "Streams", "tempo", "danceability", "energy"]]
df.head()

,Rank,Artist,Track Name,Artist_popularity,Streams,tempo,danceability,energy
0,1.0,Ava Max,Sweet but Psycho,87,1166185736,133.002,0.719,0.704
1,2.0,Billie Eilish,bad guy,98,1052358787,135.128,0.701,0.425
2,3.0,Ariana Grande,7 rings,97,789094044,140.048,0.778,0.317
3,4.0,Tones and I,Dance Monkey,92,764208309,98.078,0.825,0.593
4,5.0,Shawn Mendes,Señorita,94,763064359,116.967,0.759,0.548